### ISSUE TITLE
Awesome! Any plan to support Swift 3.0?

### ISSUE THREAD

**Issue by allenwong** [ankitthakur/SwiftPing#6]
Do you have any play to support swift 3.0?
Really hope can bring this pod to my project.

**Comment by ankitthakur** [comment]
Working on it @allenwong. If you will get time to migrate it to swift3, then you can create a pull request.

**Comment by kaishin** [comment]
@ankitthakur Is there any progress being made? I'd love to help but I want to make sure I do not end up doing stuff that you already did. Maybe having a `swift3` branch could help keep others in the loop and allow them to contribute if possible.

**Comment by allenwong** [comment]
@kaishin Looking very much forward the Swfit 3 branch. Thanks in advance!

**Comment by Laban1** [comment]
+1

**Comment by ankitthakur** [comment]
The master branch is now updated with Swift 3.
